### ISSUE TITLE
test: saving and loading peers from a file is flaky in CI

### ISSUE THREAD

**Issue by dignifiedquire** [n0-computer/iroh#1686]
```
failures:

---- magicsock::endpoint::tests::load_save_peer_data stdout ----
thread 'magicsock::endpoint::tests::load_save_peer_data' panicked at iroh-net/src/magicsock/endpoint.rs:1954:44:
called `Result::unwrap()` on an `Err` value: failed renaming peer data file

Caused by:
    Invalid cross-device link (os error 18)

---- magic_endpoint::tests::save_load_peers stdout ----
thread 'magic_endpoint::tests::save_load_peers' panicked at iroh-net/src/magic_endpoint.rs:710:62:
called `Option::unwrap()` on a `None` value


failures:
    magic_endpoint::tests::save_load_peers
    magicsock::endpoint::tests::load_save_peer_data

```

https://github.com/n0-computer/iroh/actions/runs/6585342663/job/17891575214?pr=1674

**Comment by dignifiedquire** [comment]
@flub @divagant-martian maybe you have any ideas

**Comment by dignifiedquire** [comment]
Fixed by https://github.com/n0-computer/iroh/pull/1674/commits/723a89754bb0843ed6b6a49db5e676e3d81a7e4e
