### ISSUE TITLE
Iroh doctor derp-regions panics

### ISSUE THREAD

**Issue by rklaehn** [n0-computer/iroh#1824]
```
❯ ./target/release/iroh doctor derp-regions
Round 1/5
thread 'main' panicked at iroh/src/commands/doctor.rs:799:13:
assertion failed: !client.is_connected().await?
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

```
❯ RUST_BACKTRACE=1 ./target/release/iroh doctor derp-regions
Round 1/5
thread 'main' panicked at iroh/src/commands/doctor.rs:799:13:
assertion failed: !client.is_connected().await?
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
   1: core::panicking::panic_fmt
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
   2: core::panicking::panic
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:117:5
   3: iroh::commands::doctor::derp_regions::{{closure}}
             at ./iroh/src/commands/doctor.rs:799:13
   4: iroh::commands::doctor::run::{{closure}}
             at ./iroh/src/commands/doctor.rs:996:41
   5: iroh::commands::Cli::run::{{closure}}
             at ./iroh/src/commands.rs:143:53
   6: iroh::main_impl::{{closure}}
             at ./iroh/src/main.rs:36:17
   7: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at /Users/rklaehn/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.34.0/src/runtime/park.rs:282:63
   8: tokio::runtime::coop::with_budget
             at /Users/rklaehn/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.34.0/src/runtime/coop.rs:107:5
   9: tokio::runtime::coop::budget
             at /Users/rklaehn/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.34.0/src/runtime/coop.rs:73:5
  10: tokio::runtime::park::CachedParkThread::block_on
             at /Users/rklaehn/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.34.0/src/runtime/park.rs:282:31
  11: tokio::runtime::context::blocking::BlockingRegionGuard::block_on
             at /Users/rklaehn/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.34.0/src/runtime/context/blocking.rs:66:9
  12: tokio::runtime::scheduler::multi_thread::MultiThread::block_on::{{closure}}
             at /Users/rklaehn/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.34.0/src/runtime/scheduler/multi_thread/mod.rs:87:13
  13: tokio::runtime::context::runtime::enter_runtime
             at /Users/rklaehn/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.34.0/src/runtime/context/runtime.rs:65:16
  14: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
             at /Users/rklaehn/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.34.0/src/runtime/scheduler/multi_thread/mod.rs:86:9
  15: tokio::runtime::runtime::Runtime::block_on
             at /Users/rklaehn/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.34.0/src/runtime/runtime.rs:350:50
  16: iroh::main
             at ./iroh/src/main.rs:18:5
  17: core::ops::function::FnOnce::call_once
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by dignifiedquire** [comment]
is this still an issue?

**Comment by divagant-martian** [comment]
tested this on current main (a42c1b2) and it's still an issue. Now the command is `iroh doctor derp-urls`

**Comment by divagant-martian** [comment]
it seems to be this is no longer an issue
