### ISSUE TITLE
flaky test: client::blobs::tests::test_blob_delete_mem

### ISSUE THREAD

**Issue by dignifiedquire** [n0-computer/iroh#2730]
https://github.com/n0-computer/iroh/actions/runs/10882462642/job/30193563352

```
failures:

failures:
    client::blobs::tests::test_blob_delete_mem

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 29 filtered out; finished in 1.69s


--- STDERR:              iroh client::blobs::tests::test_blob_delete_mem ---
thread 'client::blobs::tests::test_blob_delete_mem' panicked at iroh\src\client\blobs.rs:1594:9:
assertion failed: hashes.is_empty()
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\std\src\panicking.rs:665
   1: core::panicking::panic_fmt
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\core\src\panicking.rs:74
   2: core::panicking::panic
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library\core\src\panicking.rs:148
   3: iroh::client::blobs::tests::test_blob_delete_mem::async_block$0
             at .\src\client\blobs.rs:1594
   4: core::future::future::impl$1::poll<ref_mut$<dyn$<core::future::future::Future<assoc$<Output,enum2$<core::result::Result<tuple$<>,anyhow::Error> > > > > > >
             at /rustc/eeb90cda1969[383](https://github.com/n0-computer/iroh/actions/runs/10882462642/job/30193563352#step:10:384)f56a2637cbd3037bdf598841c\library\core\src\future\future.rs:123
   5: core::future::future::impl$1::poll<ref_mut$<core::pin::Pin<ref_mut$<dyn$<core::future::future::Future<assoc$<Output,enum2$<core::result::Result<tuple$<>,anyhow::Error> > > > > > > > >
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c\library\core\src\future\future.rs:123
   6: tokio::runtime::scheduler::current_thread::impl$8::block_on::closure$0::closure$0::closure$0<core::pin::Pin<ref_mut$<core::pin::Pin<ref_mut$<dyn$<core::future::future::Future<assoc$<Output,enum2$<core::result::Result<tuple$<>,anyhow::Error> > > > > > > > >
             at C:\Users\Administrator\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.38.1\src\runtime\scheduler\current_thread\mod.rs:659
   7: tokio::runtime::coop::with_budget
             at C:\Users\Administrator\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.38.1\src\runtime\coop.rs:107
   8: tokio::runtime::coop::budget
             at C:\Users\Administrator\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.38.1\src\runtime\coop.rs:73
   9: tokio::runtime::scheduler::current_thread::impl$8::block_on::closure$0::closure$0<core::pin::Pin<ref_mut$<core::pin::Pin<ref_mut$<dyn$<core::future::future::Future<assoc$<Output,enum2$<core::result::Result<tuple$<>,anyhow::Error> > > > > > > > > >
             at C:\Users\Administrator\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.38.1\src\runtime\scheduler\current_thread\mod.rs:659
  10: tokio::runtime::scheduler::current_thread::Context::enter<enum2$<core::task::poll::Poll<enum2$<core::result::Result<tuple$<>,anyhow::Error> > > >,tokio::runtime::scheduler::current_thread::impl$8::block_on::closure$0::closure_env$0<core::pin::Pin<ref_mut$<
             at C:\Users\Administrator\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.38.1\src\runtime\scheduler\current_thread\mod.rs:404
  11: tokio::runtime::scheduler::current_thread::impl$8::block_on::closure$0<core::pin::Pin<ref_mut$<core::pin::Pin<ref_mut$<dyn$<core::future::future::Future<assoc$<Output,enum2$<core::result::Result<tuple$<>,anyhow::Error> > > > > > > > > >
             at C:\Users\Administrator\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.38.1\src\runtime\scheduler\current_thread\mod.rs:658
  12: tokio::runtime::scheduler::current_thread::impl$8::enter::closure$0<tokio::runtime::scheduler::current_thread::impl$8::block_on::closure_env$0<core::pin::Pin<ref_mut$<core::pin::Pin<ref_mut$<dyn$<core::future::future::Future<assoc$<Output,enum2$<core::resu
             at C:\Users\Administrator\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.38.1\src\runtime\scheduler\current_thread\mod.rs:737
  13: tokio::runtime::context::scoped::Scoped<enum2$<tokio::runtime::scheduler::Context> >::set<enum2$<tokio::runtime::scheduler::Context>,tokio::runtime::scheduler::current_thread::impl$8::enter::closure_env$0<tokio::runtime::scheduler::current_thread::impl$8::
             at C:\Users\Administrator\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.38.1\src\runtime\context\scoped.rs:40
  14: tokio::runtime::context::set_scheduler::closure$0<tuple$<alloc::boxed::Box<tokio::runtime::scheduler::current_thread::Core,alloc::alloc::Global>,enum2$<core::option::Option<enum2$<core::result::Result<tuple$<>,anyhow::Error> > > > >,tokio::runtime::schedul
             at C:\Users\Administrator\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.38.1\src\runtime\context.rs:180
  15: std::thread::local::LocalKey<tokio::runtime::context::Context>::try_with<tokio::runtime::context::Context,tokio::runtime::context::set_scheduler::closure_env$0<tuple$<alloc::boxed::Box<tokio::runtime::scheduler::current_thread::Core,alloc::alloc::Global>,e
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c\library\std\src\thread\local.rs:283
  16: std::thread::local::LocalKey<tokio::runtime::context::Context>::with<tokio::runtime::context::Context,tokio::runtime::context::set_scheduler::closure_env$0<tuple$<alloc::boxed::Box<tokio::runtime::scheduler::current_thread::Core,alloc::alloc::Global>,enum2
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c\library\std\src\thread\local.rs:260
  17: tokio::runtime::context::set_scheduler<tuple$<alloc::boxed::Box<tokio::runtime::scheduler::current_thread::Core,alloc::alloc::Global>,enum2$<core::option::Option<enum2$<core::result::Result<tuple$<>,anyhow::Error> > > > >,tokio::runtime::scheduler::current
             at C:\Users\Administrator\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.38.1\src\runtime\context.rs:180
  18: tokio::runtime::scheduler::current_thread::CoreGuard::enter<tokio::runtime::scheduler::current_thread::impl$8::block_on::closure_env$0<core::pin::Pin<ref_mut$<core::pin::Pin<ref_mut$<dyn$<core::future::future::Future<assoc$<Output,enum2$<core::result::Resu
             at C:\Users\Administrator\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.38.1\src\runtime\scheduler\current_thread\mod.rs:737
```

**Comment by ramfox** [comment]
no longer a test on iroh-blobs
